error message corrected

diff --git a/bin/flatcar-install b/bin/flatcar-install
--- a/bin/flatcar-install
+++ b/bin/flatcar-install
@@ -13,7 +13,7 @@ else
 fi
 
 if flag == 0; then
-    command -v bzip2 > /dev/null || { echo "error: command 'wget' not found" > /dev/stderr ; exit 1 ; }
+    command -v bzip2 > /dev/null || { echo "error: command 'bzip2' not found" > /dev/stderr ; exit 1 ; }
 fi
 
 command -v mkfifo > /dev/null || { echo "error: command 'mkfifo' not found" > /dev/stderr ; exit 1 ; }
